### PR TITLE
Add Quilted Fabric API Icon(s) + Proposition to design Icons for all 8 "main" QSLs

### PR DESCRIPTION
**Pull request by Azagwen**
Hi!

This PR contains an Icon for the `Quilted Fabric api` QSL, in scales from 32x to 2048x in PNG format, and in SVG.
This icon was selected following discussions in Quilt's Toolchain server, after which I was allowed to design an Icon for the `Quilted Fabric api` QSL, the Icon in this PR is the one that received the most votes from everyone out of my 7 initial propositions.

I'm willing to design professional looking Icons derived from Quilt's graphic identity for all of the 8 Main QSL! As long as the people in charge of each QSL and QSL in general are fine with it.

### CODE REVIEW

**Comment by gdude2002** [comment]
Looking fantastic so far! A few things to note:

1. Are you okay with using the CC0 for this? Branding really needs to be CC0 in order for us to properly make use of it across our mediums - if not, that's OK, it'll just limit where we can use it as not everywhere has a good way to provide proper credit. We'll still provide credit where we can though, of course.
2. Are you creating these in vector or raster format? If the former, it'd be great to upload a vector format as well so we can easily tweak and re-export at different sizes as needed.

Otherwise, absolutely loving your work so far!

**Comment by Azagwen** [comment]
> Looking fantastic so far! A few things to note:
> 
> 1. Are you okay with using the CC0 for this? Branding really needs to be CC0 in order for us to properly make use of it across our mediums - if not, that's OK, it'll just limit where we can use it as not everywhere has a good way to provide proper credit. We'll still provide credit where we can though, of course.
> 2. Are you creating these in vector or raster format? If the former, it'd be great to upload a vector format as well so we can easily tweak and re-export at different sizes as needed.
> 
> Otherwise, absolutely loving your work so far!

Glad you like them! ^^

1. I can change to whatever license is most convenient for you guys, I originally decided on CC-BY for credit as you mentioned, but if it's too restrictive, I'm 100% fine changing it!
2. These are vector yes! I just forgot to include the SVG 😅 I can push it rq

**Comment by gdude2002** [comment]
That's great, thanks for doing that o7

Given that this PR includes a proposal, should it remain open until discussed?

**Comment by Azagwen** [comment]
Well the `Quilted Fabric API` icon seems to have been accepted by the people in charge of its QSL, from what was discussed in the Toolchain Server.

For any future Icon propositions, I guess It can remain Open until I have no more Icons to propose / no more Icons accepted by the respective devs of each QSL ^^

**Comment by gdude2002** [comment]
These all look fantastic so far - I'd support a push to create icons for all the modules, as long as each team signs off on the icons you propose.

**Comment by gdude2002** [comment]
While we 100% appreciate the effort you've put into these icons, it's been almost a year since there was any activity on this PR - so I'm going to close it for inactivity.

In the meantime I've thrown together some team icons, b/c, well, we needed 'em, and nobody else really had the time or spoons. They're pretty poor in comparison to your work, so if you feel like picking this up again, we'd love to chat!

**Pull request closed without merging**
