### PR TITLE
Compressed all CC0 images with `oxipng -so max`

### PR DESCRIPTION
**Pull request by ImperatorStorm**

### CODE REVIEW

**Review by wafflecoffee — APPROVED** [review]

**Comment by gdude2002** [comment]
This is completely unnecessary, imo. The images are not exactly large as they are, many things are vectors, and I really don't want to risk losing any quality.

**Comment by Tkain** [comment]
> This is completely unnecessary, imo. The images are not exactly large as they are, many things are vectors, and I really don't want to risk losing any quality.

[Oxipng](https://github.com/shssoichiro/oxipng) is a lossless compressor, meaning that any image compressed with it will be the exact same pixel-for-pixel; you won't need to worry about any quality loss. And considering how this compression saves about 50% of the original files' size on average, I think this PR is seriously worth reconsidering.

**Comment by OroArmor** [comment]
> FWIW this won't make the repo smaller (it is even the opposite) as the full quality images will still be part of the history. 

This is still true. So the repository size is just 150% the original size instead of what it is currently.

**Comment by wafflecoffee** [comment]
Is the repository size really what matters here? Only a few people are actually going to be pulling from here, and everyone else is going to be seeing the copy that those few people pulled. Having the small copy of an image saves on bandwidth considerably for those of us with a pretty bad internet connection (for example, me), and believe me, every small bit helps.

**Comment by EnnuiL** [comment]
What's the problem of optimizing images?
Well, yes, the repo might get a bit bigger, but does it really matter? The repository isn't the only place were the art will be used, and I don't think people are really going to clone them locally (except for actually doing git stuff), they're just gonna press that big "Download ZIP" button, and that doesn't download any git metadata;
What if a modded launcher for example wants to use a Quilt logo? What if someone wants to add a little Quilt badge saying "Yes, we support Quilt", wouldn't it be nice to save few bytes everywhere it'll being used? What if you want to grab the 128x logo for QSL but the image was too heavy? (iirc, that was indeed a problem, although that was solved through other means)
There are many usages for using the raster versions of the images, and it would be fair to provide the raster images as losslessly optimized, and oxipng is excellent for that
So yeah, don't think about as a "it reduces the repository's size", think about it more as a "it reduces the size of images that can be potentially be used by other places, such as modded launchers"

**Comment by gdude2002** [comment]
I think that's a fairly solid point - however, I'm not sure it's that useful to manually compress/optimise them via a PR. It'd be better if we could automate this somehow - any ideas?

**Comment by Akarys42** [comment]
> I think that's a fairly solid point - however, I'm not sure it's that useful to manually compress/optimise them via a PR. It'd be better if we could automate this somehow - any ideas?

We could setup a github action workflow that compresses any new image, I guess. I think what we should be looking at is having smaller copies of the same image though, like some 64x64 and 128x128.

**Comment by gdude2002** [comment]
I think that could work as a first step - resizing I'm not sure about, as we do provide vector formats where possible so people can make their own exports, but I think we probably do want some guidelines somewhere.

**Pull request closed without merging**
