### PR TITLE
Zoomeyes

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
for the Quilters that see something crazy!

Gotta go fast!

I have no clue what else to put here lol

### CODE REVIEW

**Comment by TelepathicGrunt** [comment]
dang it, I thought the thinknoodog would've made a separate pr. my bad

**Comment by Prospector** [comment]
We need to consider the licensing situation, currently if we merged this PR we would be licensing these images as CC0, which I don't think we have the right to? Using them as merely an emoji tends to be more socially acceptable, much like memes (which are debatably still copyright infringement), but hosting them in a GitHub repo under a specific license seems a bit too far imo.

**Comment by TelepathicGrunt** [comment]
I was going by this in order to submit emojis that quilt discord can add. https://github.com/QuiltMC/quiltmc.org/pull/11

**Comment by gdude2002** [comment]
Hey, sorry for taking so long to get back to you - we were still getting a few things set up, organizationally.

For the time being, we've decided we're going to close all emoji-related PRs. The main reason for this is that we haven't had a chance to sit down and discuss where we'd actually like to go with our emoji set - my gut instinct says we'll probably look for patches, but for the time being, we're just not sure.

Keep an eye out on the server for a discussion at some point!

**Pull request closed without merging**
