### PR TITLE
Prideapples!

### PR DESCRIPTION
**Pull request by Fusion-Flux**
Added some pride flag pineapples!

### CODE REVIEW

**Comment by gdude2002** [comment]
Thanks! I can't review this right now (since I'd need to open up Blockbench to check them all, GH just isn't suitable for this) - maybe you could provide a screenshot of each?

**Review by sschr15 — APPROVED** [review]
iapprove

**Comment by gdude2002** [comment]
Dangit fusion, I meant attach them in a PR comment lmao

**Comment by gdude2002** [comment]
:+1:

**Pull request merged**
