### PR TITLE
New pride banner design

### PR DESCRIPTION
**Pull request by Akarys42**
# Changes 

This new design removes the progress flag from the background of banner, and replace it with the normal pride flag.

This change comes after a few users pointing us at the controversies around this flag.

I also made the background lighter to make it clearer to see.

# Reasoning

Courtesy of @gdude2002:

This flag, including trans and bipoc colors, is controversial in the LGBT community, as it implies those people weren't included in the original flag, which doesn't make sense when [considering the origins of the movement](https://en.wikipedia.org/wiki/Stonewall_riots). For those reasons, we decided to switch the flag to the normal rainbow one.

# Preview

### CODE REVIEW

**Comment by Scotsguy** [comment]
Are the changes apart from the pride flag itself intentional?
All pride patches except for one have lost all but their base colour, and they're no longer transparent

**Comment by FnigePython** [comment]
Yeah where did all except 1 flag go?

**Comment by Akarys42** [comment]
RIght, I somehow didn't notice most flags are missing. The transparency change is on purpose, though, with the Discord compression it is totally unreadable.

**Comment by gdude2002** [comment]
This needs to be done with a tool supporting Affinity's project format, so the project files are updated. Affinity is the most affordable professional editing suite, which is why I picked it - though of course, Linux-based machines (like Chromebooks) can't run it, Linux was never the operating system of choice for graphic design.

I'll do this myself soonish, but I'm not sure when.

**Comment by Akarys42** [comment]
The patch issue has been fixed, and the file now uses Affinity. As a side note, we should be looking into having source files in the repository that can be opened by free software, but this is another issue.

**Comment by gdude2002** [comment]
> we should be looking into having source files in the repository that can be opened by free software

In an ideal world, yes - however, there is no free software package for the kind of artwork we provide project files for that is ergonomic and friendly to work in for the majority of artists, and Affinity is the most affordable professional suite that I can think of. That's why I picked it!

---

There have been some discussions on Discord with users asking why this change is being made. We've had a chat about it there, but Discord is not a good place for that discussion to remain for the sake of keeping information available and easy to find, so I'm going to summarize it below.

 # Why not use the progress flag?

In order to answer this question, we need to look at the history of LGBT pride flags. To give a quick overview

- **1978**: The rainbow flag is flown at the Gay Freedom Day Parade in San Francisco, for the first time
- **2017**: The Philadelphia Pride flag (with black and brown stripes) was flown for a local pride event in Philadelphia
- **2018**: The Progress Pride Flag is created by Daniel Quasar
- **2021**: Intersex Equality Rights UK comes up with their version of the Progress Pride Flag, including the Intersex Pride Flag

The original rainbow flag was designed to represent the entire LGBT+ community, regardless of creed, ethnicity, identity or sexuality. Pride movements such as Stonewall were spearheaded by Black trans women, among other groups - and the rainbow flag was created with the explicit intention to include those people. Part of the criticism that I've seen regarding the Progress Pride flag is that, by adding stripes that represent these communities, the Progress Pride flag implies that those groups were not represented by the original rainbow pride flag - and that by trying to replace the rainbow flag as a global symbol of Pride, we'll end up with a situation where the rainbow flag ends up being used only by the white, cis side of the LGBT community.

As [The Atlantic notes](https://www.theatlantic.com/culture/archive/2021/06/pride-flag-has-representation-problem/619273/):

> Pride flags and parades are seen as symbolically representative of the queer community’s fight for liberation. However, as more corporate sponsorships leak into the festivities, some people see the events as being at odds with the historical movement and the rainbow flag’s progressive ethos. Amari told me that she loves Pride as a time to celebrate her queer ancestors and continue their political work. However, the predominantly white and cisgender nature of many mainstream Pride events leaves her feeling physically unsafe and politically isolated. Damarjian expressed similar concerns, pointing to partnerships between the Utah Pride Center and [arms manufacturers](https://utahpridecenter.org/wp-content/uploads/2021/03/Annual-Report-2021-v2.pdf), such as [L3Harris](https://asbarez.com/artsakh-republic-sues-defense-contractor-over-war-crimes-and-crimes-against-humanity/) and [Northrop Grumman](https://www.middleeasteye.net/news/israel-palestine-which-countries-companies-arming), as well as companies such as [Wells Fargo](https://www.sltrib.com/news/2018/05/30/just-days-before-the-big-parade-an-open-letter-pushes-the-utah-pride-center-to-drop-national-banks-as-sponsors/), which [invested in the Dakota Access Pipeline](https://www.yesmagazine.org/issue/good-money/2019/01/02/standing-rocks-surprising-legacy-a-push-for-public-banks).
> 
> These issues reflect long-standing contention over the use of Pride’s official symbols for the sake of “[pinkwashing](https://theconversation.com/the-rise-of-pride-marketing-and-the-curse-of-pink-washing-30925),” the deployment of ostensibly LGBTQ-friendly discourse by corporations and governments to obscure their participation in oppression and occupation. This includes [military contractors going rainbow](https://www.vice.com/en/article/z3xmk8/companies-are-using-pride-month-to-rainbow-wash-bombs-and-tasers) as a PR-friendly spin, and former presidential candidates like Pete Buttigieg slapping [the anti-racist Philadelphia flag](https://attitude.co.uk/article/pete-buttigieg-adopts-black-and-brown-striped-pride-flag-for-official-merch/20958/) on their 2020 campaign merch while supporting policies that endanger [Black and brown people](https://prospect.org/civil-rights/african-americans-already-know-pete-buttigieg-very-well/).

The concerns regarding pinkwashing and capitalistic tendencies aren't new to the LGBT community, especially as companies appropriate LGBT symbolism and flags as a sick form of advertising, something that we're all very familiar with given [how companies behave on (and after) pride month](https://twitter.com/kekeflipnote/status/1532407020741173251). [M. J. Murphy,
Prof. of Gender & Sexuality Studies, points out](https://emjaymurphee.medium.com/we-dont-need-a-new-pride-flag-efc883e0817b):

> Quasar’s design has attracted a lot of buzz and a Kickstarter [campaign](https://www.kickstarter.com/projects/danielquasar/progress-a-pride-flag-reboot/description) to mass-produce the new flag raised almost twice as much as the original $14,000 goal. Quasar has since commercialized that design, [selling a range of products](https://quasar.digital/shop/?v=a284e24d5f46) featuring the Progress flag and [licensing](https://quasar.digital/shop/terms/?v=a284e24d5f46) it to other manufacturers. Unlike the original rainbow Pride flag, Quasar’s flag is not in the public domain.
> 
> Both proposals for new pride flags are well-intended: a desire to create an inclusive visual symbol of the diverse LGBTQ+ community and raise awareness of those still marginalized within that community and the wider society. They respond to real, enduring problems and deserve to be taken seriously and considered on their merits.
> 
> Nevertheless, my initial reaction to both new flags was similar: they’re flagrantly disrespectful of an historic symbol of LGBTQ+ people, pride, and community. And, on closer analysis, I came to understand them as narrow statements of identity politics that invite the very kinds of division they claim to remedy.

Concerns deepen further when we look at the newer variant of the progress flag, designed by Intersex Equality Rights UK - which adds the purple circle and yellow background of the Intersex Pride flag. As mentioned in [the above article from The Atlantic](https://www.theatlantic.com/culture/archive/2021/06/pride-flag-has-representation-problem/619273/):

> Natalia Shmueli, a 25-year-old tech entrepreneur in Tennessee shares Monts’s skepticism. “I am happy to see [intersex health care](https://www.pbs.org/newshour/health/the-fight-to-end-intersex-surgeries-at-a-top-hospital-took-a-deep-toll-on-activists) being taken more seriously within medical contexts,” she told me, referring to the ongoing fight to end surgeries forced on people born with intersex characteristics. “Still, I don’t think cutesy flags actually highlight anything for LGBT [people] other than [making] us look kitschy and marketable.” Shmueli argued that tacking the intersex symbol on to the Pride flag inaccurately lumps intersex issues together with the broader LGBTQ imagined community, noting that the experiences of intersex people are often invoked without context or complexity, ultimately benefiting no one.

Indeed, this is a fairly common complaint from the intersex community - their issues are so unique and nuanced that they often lament being bundled in with the rest of the LGBT community, which erases their unique struggles and makes it difficult for them to seek the rights and medical care they need.

---

For a look at the other side of the coin, we can take a look at [this excellent article by Forbes](https://www.forbes.com/sites/jamiewareham/2020/07/12/why-lgbt-people-have-started-using-a-new-pride-flag-nhs-black-lives-matters/?sh=1b001b5a125a), which digs into some of the thought process behind flags like the Progress Pride flag. However, this article does make a fairly salient point too:

> “I have noticed an increase in the flag’s use by white cis male homosexuals as well as in spaces typically inhabited by this group of people such as London and Manchester’s G-A-Y now,” Ridwan adds.
> 
> “I’d like to think recent events the world has faced have allowed for a refocusing of our attention on the issues affecting those most vulnerable. So, the use of the progress flag, hopefully, means an increased awareness of intersecting forms of oppression, and therefore the need for intersectional inclusion.
> 
> “However, actions of solidarity must outmatch virtue signalling. As we see a rise in prominence of racist and transphobic rhetoric in the U.K., awareness must lead to positive change.

---

Additional discussion on Discord have seen trans community members pointing out that they believe the landscape has changed since these discussions took place, and they may well be right. However, if that is the case, one would need to be willing to show that all the concerns mentioned above have been addressed, and we just don't have the data to support that conclusion. Realistically, Quilt must represent the LGBT+ community in ways that match how it wishes to represent itself, and doing so requires using iconography that doesn't step on the feet of people with concerns like this.

That's not to say that we believe those that use the Progress Pride flag are wrong to do so, or that the way they view their own identity and sexuality (or the representation thereof) is invalid - it's just clear that, at least right now, the Progress Pride flag is not for us.

**Comment by gdude2002** [comment]
Anyway, good work - thanks!

**Pull request merged**
